import groovy.json.JsonOutput
import groovy.json.JsonSlurper
import java.time.Instant
import java.time.ZoneId
import java.time.ZonedDateTime
import java.time.format.DateTimeFormatter

/**
A helper Groovy class containing method to export workflow parameters
*/

class JsonWorkflowParamExporter {

    /**
    @param passed_params_map                        map of parameters passed to a workflow by a user
    @param paramsMapFull                          parameter map generated by paramsSummaryMap from nf-schema plugin
    @param workflowMetadata                        a WorkflowMetadata object (info: e.g. workflow duration)
    @param nextflowVersion                         Nextflow version (property from Nextflow metadata object)
    @param idat_count                               Number of IDAT files in input directory
    @param sample_count                             Number of processed samples (in sample sheet)
    */

    Map passedParamsMap
    Map paramsMapFull
    def workflowMetadata
    String nextflowVersion
    Instant workflowStart

    JsonWorkflowParamExporter(
        Map passedParamsMap,
        Map paramsMapFull,
        def workflowMetadata,
        String nextflowVersion,
        Instant workflowStart
    ) {
        this.passedParamsMap = passedParamsMap
        this.paramsMapFull = paramsMapFull
        this.workflowMetadata = workflowMetadata
        this.nextflowVersion = nextflowVersion
        this.workflowStart = workflowStart
    }

    String formatInstant(Instant instant) {
        def zoned = ZonedDateTime.ofInstant(instant, ZoneId.systemDefault())
        def formatter = DateTimeFormatter.ofPattern("dd MMMM yyyy HH:mm:ss", java.util.Locale.ENGLISH)
        return zoned.format(formatter)
    }

    Map getFlattenedPassedParamsMap() {
        def flatMap = this.passedParamsMap.clone()
        
        flatMap['Container_engine'] = this.paramsMapFull['Core Nextflow options']['containerEngine']
        flatMap['Container_R_sesame'] = this.paramsMapFull['Core Nextflow options']['container']['withLabel:r_sesame']
        flatMap['Container_R_clock'] = this.paramsMapFull['Core Nextflow options']['container']['withLabel:r_clock']
        flatMap['Container_Python'] = this.paramsMapFull['Core Nextflow options']['container']['withLabel:python']
        flatMap['nextflowVersion'] = this.nextflowVersion
        flatMap['Workflow_start'] = this.formatInstant(this.workflowStart)
        // Timezone-independent start instant (UTC epoch seconds) so a container
        // (typically UTC) can compute an accurate run duration regardless of the
        // host timezone used to format Workflow_start above.
        flatMap['Workflow_start_epoch'] = this.workflowStart.getEpochSecond()
        flatMap['Workflow_complete'] = this.workflowMetadata.complete
        flatMap['Workflow_success'] = this.workflowMetadata.success
        flatMap['Workflow_errMsg'] = this.workflowMetadata.errorMessage
        flatMap['Workflow_errDetails'] = this.workflowMetadata.errorReport
        flatMap['Workflow_exitStatus'] = this.workflowMetadata.exitStatus
        flatMap['Workflow_cmdLine'] = this.workflowMetadata.commandLine
    
        flatMap.remove('container')

        return(flatMap)
    }

    /**
    Function saving workflow parameters to JSON file (params.json) in an output directory

    @return formated JSON string
    */
    String toJSON() {
        
        def jsonSlurper = new JsonSlurper()
        def flatMap = this.getFlattenedPassedParamsMap()
        def jsonParams = JsonOutput.toJson(flatMap)
        return JsonOutput.prettyPrint(jsonParams)
    }
}